### ISSUE TITLE
New software name

### ISSUE THREAD

**Issue by ghost** [spk121/zile#4]
The original ligthweight clone of Emacs was renamed Zemacs because [Zile has become a text editor development kit](https://www.gnu.org/software/zile/) since a few years. Zz is another implementation of a ligthweight Emacs clone that uses Lua as an extension language.

Actually, this software is actually a clone of Emacs like Zz and not a fork of Zile despite his name "Zile on Guile" or Zile. 

Could you choose a new software name?

**Comment by spk121** [comment]
If you go right now to the zile.git repo on https://git.savannah.gnu.org/cgit/zile.git and look in the master branch, it is GNU Zile, the C edition, where the editor is named `zile`.   You'll find that GNU Zile, the Lua edition, hasn't been updated since 2014 while C Zile is still being updated in 2019.

This project is a fork of GNU Zile, the C edition.  Most of the sources come from GNU Zile and bears its copyright.

I haven't emailed Ruben Thomas in a long time, so I don't know what his future plans are, but, the git repo suggests that  future release of Zile with be C Zile where the editor is named `zile` and that the Lua Zile project is something he lost interest in.

This project, `zile-on-guile` is rarely and randomly rebased of the master branch of zile, so if it is still zile in the master branch there, it makes sense to leave it zile here.
